// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okrwmprauswcaftdoiss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rcndtcHJhdXN3Y2FmdGRvaXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjc3OTYsImV4cCI6MjA2ODcwMzc5Nn0.6WQuV8Ba96O4rjW4KamLu9C6iYYwdTHK84yi78ZVkvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});